/*alert("JavaScript works!");
*
* Woody Wilde
* SDI 1210
* 09/26/12
* Project 1
*/

//declaring variables
var boyName = "Bobby";
var owl = "\"let's find out.\"";
var sucker = "Tootsie Roll TootsiePop";
var stick = true;
var licks = 5;

//variable output via console.log
console.log(boyName + "Ask's Mr. Owl, \"how many lick's does it take to get to the center of a tootsie roll tootsie pop?\"");
console.log("Mr. Owl says \"" + owl + "\"");
console.log("Mr. Owl counts up to " + licks + " and says, " + licks);
console.log(boyName + " asked Mr.owl if he still had the stick, and Mr. Owl said this was " + stick);
console.log("Now all " + boyName + " will eat is a " + sucker + ".");

//code execution

if (stick === true) {
	console.info("This is important information.");
	if (licks <= 3) {
		licks = licks + 1;
		console.log("Three licks was all it took.");
			if (boyName === "John") {
				console.log(boyName + "could not believe Mr. Owl ate his " + sucker);
	} else {
		console.log("I think it would take more than three licks.");
} else {
		if (boyName === "John") {
				console.log(boyName + "could not believe Mr. Owl ate his " + sucker);
	} else {
};

